<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBiwxlse\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBiwxlse/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBiwxlse.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBiwxlse\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBiwxlse\appProdProjectContainer([
    'container.build_hash' => 'Biwxlse',
    'container.build_id' => 'eadf7bb4',
    'container.build_time' => 1691634741,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBiwxlse');
